### ISSUE TITLE
`uts-46 mapping step, should agree with icu4j's uts46-mapping step` failure

### ISSUE THREAD

**Issue by armanbilge** [typelevel/idna4s#90]
b359510063d1587eeaa2147ffbe24db1145c6afb

https://github.com/typelevel/idna4s/actions/runs/4388134318/jobs/7684272460#step:10:164

```
==> X org.typelevel.idna4s.tests.uts46.CodePointMapperTests.idna4s's uts-46 mapping step, should agree with icu4j's uts46-mapping step  0.191s munit.FailException: /home/runner/work/idna4s/idna4s/tests/jvm/src/test/scala/org/typelevel/idna4s/tests/uts46/CodePointMapperPlatformTests.scala:53
52:    }
53:  }
54:

Failing seed: 07qUdmSmex6ZFZBG6Cp6rkPgvzgAuqeFhAsJX8foMjB=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "07qUdmSmex6ZFZBG6Cp6rkPgvzgAuqeFhAsJX8foMjB="

Falsified after 63 passed tests.
> Labels of failing property: 
Expected "఼̬" but got "఼̬"
> ARG_0: "఼̬"
> ARG_0_ORIGINAL: "荠ꢏ뛥鑟仐ड़숫䘿Ҁ爫ꪡ妘㭻寠ᤜ퉣䇬瘎銘杘\u000bꤺ狐븐⁥覬ﻶ㎄㊃盚ồᒄ꺊澆랚꼞졈ᣡ嵏఼٘鬑"
    at munit.Assertions.fail(Assertions.scala:252)
    at munit.Assertions.fail$(Assertions.scala:15)
    at munit.FunSuite.fail(FunSuite.scala:11)
    at munit.ScalaCheckSuite.propToTry$$anonfun$1(ScalaCheckSuite.scala:104)
    at scala.util.Try$.apply(Try.scala:210)
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:104)
    at munit.ScalaCheckSuite.$init$$$anonfun$1$$anonfun$1$$anonfun$1(ScalaCheckSuite.scala:45)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:475)
    at munit.Suite$$anon$1.execute(Suite.scala:28)
    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
    at scala.concurrent.impl.Promise$DefaultPromise.transform(Promise.scala:128)
    at munit.internal.FutureCompat$ExtensionFuture.transformCompat(FutureCompat.scala:16)
    at munit.ScalaCheckSuite.$init$$$anonfun$1$$anonfun$1(ScalaCheckSuite.scala:47)
    at munit.Test.withBodyMap$$anonfun$1(Test.scala:34)
```

**Comment by mpilquist** [comment]
Fixed by #256
